# this is a hack for libtool, which doesn't know about SDK 11.x, so we use here 10.15 instead
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.11                  # [osx and x86_64]
  - 10.15                  # [osx and arm64]

