# this is a hack for libtool, which doesn't know about SDK 11.x, so we use here 10.15 instead
MACOSX_DEPLOYMENT_TARGET:  # [osx and arm64]
  - 10.15                  # [osx and arm64]
c_compiler_version:        # [linux]
  - 11.2.0                 # [linux]
cxx_compiler_version:      # [linux]
  - 11.2.0                 # [linux]
fortran_compiler_version:  # [linux or osx]
  - 11.2.0                 # [linux or osx]
